# Default configuration for feature extraction
features:
  enable_all: true
  available:
    - time_skewness
    - time_kurtosis
    - wavelet_energy
datasets:
  - path: iris
    label_mapping: {}
model_types:
  - RandomForest
  - XGBoost
  - LogisticRegression
  - SVM
scaling_methods:
  - standard
feature_selections:
  - null
  - featurewiz
hyperparameter_tuning: true
n_trials_optuna: 10
cv_folds: 3
test_size: 0.2
val_size: 0.2
random_state: 42
target_column: target
checkpoint_interval: 10
resume: false
